Repository Roave/no-leaks, pull requests merged in 2019-03, with the labels that each got.

#1 Detect memory leaks in test runs
  .gitattributes
  .gitignore
  .travis.install.sh
  .travis.yml
  LICENSE
  README.md
  bin/roave-no-leaks
  bin/roave-no-leaks.php
  composer.json
  infection.json.dist
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  psalm.xml.dist
  src/CollectTestExecutionMemoryFootprints.php
  src/EmptyBaselineMemoryUsageTest.php
  src/MeasuredBaselineTestMemoryLeak.php
  src/MeasuredTestRunMemoryLeak.php
  test/e2e/LeakyIntegrationTest.php
  test/e2e/phpunit-mock-suite.xml
  test/e2e/run-full-suite.phpt
  test/unit/CollectTestExecutionMemoryFootprintsTest.php
  test/unit/EmptyBaselineMemoryUsageTest.php
  test/unit/MeasuredBaselineTestMemoryLeakTest.php
  test/unit/MeasuredTestRunMemoryLeakTest.php
Labels: enhancement

#2 Corrected reference to `vendor/autoload.php`
  bin/roave-no-leaks.php
Labels: bug

#3 Remove mistyped character in readme
  README.md
Labels: documentation

#4 Edited headers to be more consistent
  README.md
Labels: documentation

#11 #8 Automatic registration of `CollectTestExecutionMemoryFootprints`
  README.md
  bin/roave-no-leaks.php
  test/e2e/phpunit-mock-suite.xml
Labels: enhancement

#10 Fix: Skip baseline memory profiles that are negative (instead of crashing)
  composer.json
  src/CollectTestExecutionMemoryFootprints.php
  src/MeasuredBaselineTestMemoryLeak.php
  test/unit/MeasuredBaselineTestMemoryLeakTest.php
Labels: bug

#12 Added release/build status badges
  README.md
Labels: documentation

#13 Skipping negative memory measurements for executed tests
  .travis.yml
  src/MeasuredTestRunMemoryLeak.php
  test/unit/CollectTestExecutionMemoryFootprintsTest.php
  test/unit/MeasuredTestRunMemoryLeakTest.php
Labels: bug

#17 Added artwork by @Pivetta
  .gitattributes
  README.md
  logo/no-leaks.blend
  logo/no-leaks.png
Labels: enhancement
